---
abstract: 'writes files atomically via rename()'
author:
  - 'Jeremy Mates, <jmates@sial.org>'
build_requires:
  Digest::SHA1: 2.10
  File::Path: 1.06
  File::Spec: 3.26
  Test::More: 0.72
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-AtomicWrite
no_index:
  directory:
    - inc
    - t
recommends:
  Digest::SHA1: 2.10
requires:
  File::Path: 1.06
  File::Temp: 0.18
  perl: 5.6.0
version: 0.96
