--- #YAML:1.0
name:               File-AtomicWrite
version:            1.10
abstract:           writes files atomically via rename()
author:
    - Jeremy Mates <jmates@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    Digest::SHA1:  0
    File::Path:    0
    File::Spec:    0
    File::Temp:    0.18
    IO::Handle:    0
    Test::More:    0
resources:
    homepage:    https://github.com/thrig/File-AtomicWrite
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/thrig/File-AtomicWrite
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
