---
abstract: 'writes files atomically via rename()'
author:
  - 'Jeremy Mates, <jmates@sial.org>'
build_requires:
  Digest::SHA1: 2.10
  ExtUtils::MakeMaker: 6.42
  File::Spec: 3.26
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-AtomicWrite
no_index:
  directory:
    - inc
    - t
recommends:
  Digest::SHA1: 2.10
requires:
  File::Path: 1.06
  File::Temp: 0.20
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.92
